### ISSUE TITLE
Agregar el total a las estadísticas de intercambio

### ISSUE THREAD

**Issue by Enzogolfetto** [sedici/Celsius3#104]
Seria útil que al final de la tabla en las estadísticas de intercambio apareciera una fila que sume el total de todos los años, o el total de todos los años seleccionados para tener ese numero rápidamente.

**Comment by jogianotti** [comment]
[commit d0548df7878abbcdea300041887f426b367b69db](https://github.com/sedici/Celsius3/commit/d0548df7878abbcdea300041887f426b367b69db)

Se agregaron totales a las tablas de intercambio
