### ISSUE TITLE
Listado de Usuarios por instituciones

### ISSUE THREAD

**Issue by Enzogolfetto** [sedici/Celsius3#21]
Realizar un filtro de usuarios por instituciones. Exportar a excel.

**Comment by jogianotti** [comment]
Enzo, actualmente en los listados de usuarios tanto de la administración como de la súper administración, desde la sección de filtros te permite filtrar los usuarios por país, ciudad e institución.

![filtros](https://user-images.githubusercontent.com/7002087/71672569-1ff76b00-2d55-11ea-9f51-f297a8a7c19f.png)

La funcionalidad de exportar a excel la incorporaría sobre ese listado, con la posibilidad de seleccionar los datos que se quieren exportar.

**Comment by jogianotti** [comment]
Se cierra el ticket. Ya se agregó la funcionalidad de descarga de información de usuarios de la instancia por fuera de este listado.
