### ISSUE TITLE
Errores y tickes

### ISSUE THREAD

**Issue by jogianotti** [sedici/Celsius3#39]
Como se hablo hoy, ante errores o alertas del sistema un usuario busca dar aviso para que se corrija el error. Para facilitar esta tarea al usuario se puede incorporar el registro de tareas al sistema de tickets desarrollado en Celsius, dándole al usuario la posibilidad de registrar el problema y agregar comentarios, a través de formularios en las paginas de error 500 y en las alertas del sistema.

Se deben combinar el registro tickets en la visualización de las alertas y las páginas de error cuando surge un problema.

**Comment by gonetil** [comment]
Para reporte de errores o sugerir mejoras, los usuarios pueden utilizar los issues de GitHub
