### ISSUE TITLE
Agregar perfil de usuario Gestion

### ISSUE THREAD

**Issue by asobrado** [sedici/Celsius3#59]
Agregar el rol usuario de gestion
Separar la funcionalidad del usuarios gestor con el usuario admin.

Crear dashboard con funcionalidad de los pedidos + alguna particular para el perfil gestion

**Comment by jogianotti** [comment]
@asobrado Esta tarea ya está resuelta. ¿Quedó algo pendiente o se puede cerrar?

**Comment by asobrado** [comment]
@jogianotti  si ya estra eso ahora la cierro, solo quedaria poner un dashboard con algo de nros para el perfil de gestion, pero depsues creamos otra tareaas
