### ISSUE TITLE
Error en visualización de pedidos.

### ISSUE THREAD

**Issue by Enzogolfetto** [sedici/Celsius3#66]
Al parecer hay inconveniente con el navegador de mozilla firefox. Usuarios de la UTN nos han informado que hay pedidos que no pueden ver y podría ser el navegador.

**Comment by jogianotti** [comment]
El desarrollo de Celsius3 se realiza principalmente sobre Firefox. Al no detectarse ningún error, no tener mas datos y no recibir nuevos reportes, se cierra esta tarea.
