### ISSUE TITLE
Problema con las ciudades 

### ISSUE THREAD

**Issue by Enzogolfetto** [sedici/Celsius3#67]
Hay un problema al editar un Usuario. Cuando se quiere poner que pertenece a la institución Facultad Regional Rosario (frro) UTN no aparece a menos que se reinicie el formulario y se omita el campo de ciudad. 
Este seria el ejemplo: 
!captura1.JPG!

Cuando filtro por Rosario en el campo de Instituciones no me aparece la Facultad Regional Rosario (frro) UTN:
!Captura2.JPG!

La única manera de que aparezca es reiniciando el formulario. Sacando el país y volviendo a ponerlo y omitir el campo de ciudad, ir directamente al de institución. 
!Captura3.JPG!

Esto puede deberse a que la UTN padre no tiene cargada ninguna ciudad y no se puede asignar una porque es una institución con varias sedes en distintas ciudades.

**Comment by asobrado** [comment]
@Enzogolfetto esto tenemos que definirlo, si tenes ue agregar la ciudad o no asi puede filtrar correctamente.

**Comment by Enzogolfetto** [comment]
Coincido pero no sabría que decidir. ¿Podríamos eliminar el campo de ciudad para las instituciones que tienen varias sedes?

**Comment by jogianotti** [comment]
Esta tarea se descarta ya que se dejó de usar el filtro por ciudad.
