### ISSUE TITLE
Distinguir solicitudes canceladas en la solapa "Solicitado"

### ISSUE THREAD

**Issue by Enzogolfetto** [sedici/Celsius3#69]
Como mejora puede ser útil que las solicitudes canceladas aparezcan tachadas o no aparezcan en la vista de los pedidos desde la solapa de "Solicitado". Esto permitiría hacer un seguimiento mas rápido de los pedidos.

Así se ve un pedido desde la solapa de Solicitado:
![Vista de la lista de solicitudes en un pedido](https://user-images.githubusercontent.com/59320415/72890364-76bae980-3cf0-11ea-88ae-c86cd079be20.JPG)
Y dentro del pedido se puede ver que algunas solicitudes han sido canceladas:
![como se puede ver hay solicitudes canceladas pero solo es visible entrando al pedido](https://user-images.githubusercontent.com/59320415/72890405-8f2b0400-3cf0-11ea-96b5-e79abe387012.JPG)

Si Celsius pudiera mostrar con texto tachado solicitudes ya canceladas seria mas eficiente porque no habría que entrar al pedido a chequear.

**Comment by jogianotti** [comment]
Enzo, ahora se muestran con un estilo de texto tachado todas las solicitudes canceladas que se muestran en los listados de la administración.

[commit cd0c18317fab1ecad99e90e5b377b385528ad68b](https://github.com/sedici/Celsius3/commit/cd0c18317fab1ecad99e90e5b377b385528ad68b)
