### ISSUE TITLE
Incorporar el tipo de material "Periódico"

### ISSUE THREAD

**Issue by rafaelcarlon** [sedici/Celsius3#70]
A partir de reiterados pedidos de diarios, se podría agregar la opción de **Periódico** como tipo de material, y modificar **Revista** por **Revista científica**, que es más específico. Asimismo, y dado que por restricciones de copyright no trabajamos con más de un capítulo por pedido, se podría mostrar una nota en el tipo de material **Libro**, que lo indique.

**Comment by asobrado** [comment]
@Enzogolfetto @rafaelcarlon el tipo de material periodico? tiene algun dato adicional? para la carga?

**Comment by rafaelcarlon** [comment]
Que yo sepa no tiene ningún tipo de identificador del estilo de ISSN o ISBN. Sólo título del periódico, nombre del artículo y autor. Quizás se podría añadir una fecha de publicación que permita ingresar mes y día, y el país de la publicación para desambiguar si tienen nombres muy generales (aunque esto último me parece que no pasa tanto).

**Comment by jogianotti** [comment]
@Enzogolfetto ¿el tipo de material Periódico se solicita por artículos?

**Comment by Enzogolfetto** [comment]
Entiendo que si.

**Comment by jogianotti** [comment]
bcbfbe0f79300f1333ddd1b85cdcd27955a9ce9f

Se agregó "Newspaper" como nuevo tipo de material para las solicitudes.
