### ISSUE TITLE
Agregado de funcionalidad de intercambio

### ISSUE THREAD

**Issue by jogianotti** [sedici/Celsius3#91]
Se necesita agregar una vista para la administración de cada instancia donde puedan ver el intercambio con una institución dada seleccionada.

**Comment by jogianotti** [comment]
Se creó un método con la funcionalidad para la obtención de la información de intercambio.

[commit 240b04093c33c98b2b340e1414d3d009a63df035](https://github.com/sedici/Celsius3/commit/240b04093c33c98b2b340e1414d3d009a63df035)

**Comment by jogianotti** [comment]
Se agrupa la información de intercambio por año

[commit ec9330036886ef9cafa05dd7b66c72f89662d030](https://github.com/sedici/Celsius3/commit/ec9330036886ef9cafa05dd7b66c72f89662d030)

**Comment by asobrado** [comment]
Se agrego filtro por anios y se agrego textos mas acordes

https://github.com/sedici/Celsius3/commit/63726ab839ca6c9aebb3d097e178fdceb05c7a76

**Comment by asobrado** [comment]
Se completo la tarea  de intercambio

https://github.com/sedici/Celsius3/commit/d42040815946db88aca5e5a50dae07e9919ea715

**Comment by jogianotti** [comment]
Se agregan traducciónes

[commit 9a1facc2301afb996e5150981e235c81a757f58d](https://github.com/sedici/Celsius3/commit/9a1facc2301afb996e5150981e235c81a757f58d)

**Comment by jogianotti** [comment]
Se corrige la consulta de obtención de datos de intercambio para la institución seleccionada, donde se toman correctamente los eventos de solicitud y recepción relacionados a esta institución.

[commit 52344d6d278f62ffa24582cf13f1f957cae8e346](https://github.com/sedici/Celsius3/commit/52344d6d278f62ffa24582cf13f1f957cae8e346)
